# Generated by Django 6.0.5 on 2026-05-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='15-minute interval timestamp', unique=True)),
                ('solar_kw', models.FloatField(help_text='PV production in kW')),
                ('load_kw', models.FloatField(help_text='Hotel demand in kW')),
                ('grid_price_eur_per_kwh', models.FloatField(help_text='Grid price in EUR/kWh')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
